words = [
    "amzn",
    "arn",
    "dotenv",
    "dropcursor",
    "entra",
    "fim",
    "fns",
    "gapcursor",
    "gpt",
    "hono",
    "huggingface",
    "idk",
    "idkhub",
    "kms",
    "linkify",
    "llm",
    "logprobs",
    "lucide",
    "mcp",
    "openai",
    "postgrest",
    "retryable",
    "sagemaker",
    "sanitization",
    "spii",
    "supabase",
    "tanstack",
    "tiptap",
    "vitest",
    "workerd",
    "xai",
    "xss",
    "zod",
]
